#include <iostream>
using namespace std;

int main()
{
 int a,b;
 cout<<"inserte el valor de a:"<<endl;
 cin>> a;
 cout<<"inserte el valor de b:"<<endl;
 cin>> b;
 
 if(a+b && a*b == a+b)//se da si cumple con las dos condiciones
{
cout<<"a+b y a*b son igules"<<endl;//si se cumple

}
 else
 
{
     cout<<"a+b y a*b son distinto"<<endl;//si no se cumple2

}
  
  
  
  
  system("PAUSE");
  return 0;
}
