#include <iostream>   
#include <cmath>      
using namespace std;

int main()
{
 float T_celsius;
    cout<<"bienvenidos al convertidor de Temperatura Celsius a Fahrenheit"<<endl<<endl;   
    cout<<"Para empezar inserte el valor de la Temperatura en Celsius:"<<endl;
    cin>>T_celsius;
    cout<<"la temperatura en Fahrenheit es:"<<(9.0/5.0)*T_celsius +32.0<<endl; 
  
  system("PAUSE");
  return 0;
}
