// PGM3-04
#include <iostream>
using namespace std;

int main()
{
  int contador;

  contador = 0;
  cout << "El valor inicial del contador es " << contador << endl;
  contador++;
  cout << "   contador es ahora " << contador << endl;
  contador++;
  cout << "   contador es ahora " << contador << endl;
  contador++;
  cout << "   contador es ahora " << contador << endl;
  contador++;
  cout << "   contador es ahora " << contador << endl;

  system("PAUSE");
  return 0;
}
