#include <iostream>
#include <iomanip>
#include<cmath>
using namespace std;

int main()
{
  float a,b,c;
  cout<<"calcula las raices de una funcion cuadratica"<<endl;
  cout<<"ingrese el valor de a:"<<endl;
  cin>>a;
  cout<<"ingrese el valor de b:"<<endl;
  cin>>b;
  cout<<"ingrese el valor de c:"<<endl;
  cin>>c;
  cout<<"el valor de x1 es:"<<sqrt(pow(b,2))+(-4*a*c)<<endl;
  
  
  
   
  system("PAUSE");
  return 0;
}   


