#include <iostream>
using namespace std;

int main()
{
  int contador,a;   //ponemos contador como una variable mas//
  contador=1; //el valor en q empieza (en este caso)
  a=1;
  cout<<"el contador vale "<<contador+a<<endl;//vale 0
  contador++;
  cout<<"el contador vale "<<contador+a<<endl;//1
  contador++;
  cout<<"el contador vale "<<contador+a<<endl;//2
  contador++;
  
  system("PAUSE");
  return 0;
}   


