#include <iostream>
using namespace std;

int main()
{
  int contador,a;   //ponemos contador como una variable mas//
  contador=1; //el valor en q empieza (en este caso)
  
  cout<<"el contador vale "<<contador<<endl;//vale 1
  contador++;
  cout<<"el contador vale "<<contador<<endl;//2
  contador++;
  cout<<"el contador vale "<<contador<<endl;//3
  contador++;
  
  system("PAUSE");
  return 0;
}   


